const constants = {
   FETCH_GAME_RESULTS_PERIOD_POINTS : "FETCH_GAME_RESULTS_PERIOD_POINTS",
   FETCH_GAME_RESULTS_PERIOD_POINTS_SUCCEEDED : "FETCH_GAME_RESULTS_PERIOD_POINTS_SUCCEEDED",
   FETCH_GAME_RESULTS_PERIOD_POINTS_FAILED : "FETCH_GAME_RESULTS_PERIOD_POINTS_FAILED",

   UPDATE_GAME_RESULTS_PERIOD_POINTS : "UPDATE_GAME_RESULTS_PERIOD_POINTS",
   UPDATE_GAME_RESULTS_PERIOD_POINTS_SUCCEEDED : "UPDATE_GAME_RESULTS_PERIOD_POINTS_SUCCEEDED",
   UPDATE_GAME_RESULTS_PERIOD_POINTS_FAILED : "UPDATE_GAME_RESULTS_PERIOD_POINTS_FAILED",

   UPDATE_GAME_RESULTS_VOID_PERIOD : "UPDATE_GAME_RESULTS_VOID_PERIOD",
   UPDATE_GAME_RESULTS_VOID_PERIOD_SUCCEEDED : "UPDATE_GAME_RESULTS_VOID_PERIOD_SUCCEEDED",
   UPDATE_GAME_RESULTS_VOID_PERIOD_FAILED : "UPDATE_GAME_RESULTS_VOID_PERIOD_FAILED",
}

export default constants;