export default {
    FETCH_BET_RESTRICTION_KEYS: 'BR::FETCH_BET_RESTRICTION_KEYS',
    FETCH_BET_RESTRICTION_KEYS_SUCCEEDED: 'BR::FETCH_BET_RESTRICTION_KEYS_SUCCEEDED',
    FETCH_BET_RESTRICTION_KEYS_FAILED: 'BR::FETCH_BET_RESTRICTION_KEYS_FAILED',

    FETCH_UNUSED_BET_RESTRICTION_KEYS: 'BR::FETCH_UNUSED_BET_RESTRICTION_KEYS',
    FETCH_UNUSED_BET_RESTRICTION_KEYS_SUCCEEDED: 'BR::FETCH_UNUSED_BET_RESTRICTION_KEYS_SUCCEEDED',
    FETCH_UNUSED_BET_RESTRICTION_KEYS_FAILED: 'BR::FETCH_UNUSED_BET_RESTRICTION_KEYS_FAILED',

    FETCH_MATRIX_DATA: 'BR::FETCH_MATRIX_DATA',
    FETCH_MATRIX_DATA_SUCCEEDED: 'BR::FETCH_MATRIX_DATA_SUCCEEDED',
    FETCH_MATRIX_DATA_FAILED: 'BR::FETCH_MATRIX_DATA_FAILED',

    FETCH_SPORT_PERIODS: 'BR::FETCH_SPORT_PERIODS',
    FETCH_SPORT_PERIODS_SUCCEEDED: 'BR::FETCH_SPORT_PERIODS_SUCCEEDED',
    FETCH_SPORT_PERIODS_FAILED: 'BR::FETCH_SPORT_PERIODS_FAILED',

    FETCH_MARKET_TYPE_GROUPS: 'BR::FETCH_MARKET_TYPE_GROUPS',
    FETCH_MARKET_TYPE_GROUPS_SUCCEEDED: 'BR::FETCH_MARKET_TYPE_GROUPS_SUCCEEDED',
    FETCH_MARKET_TYPE_GROUPS_FAILED: 'BR::FETCH_MARKET_TYPE_GROUPS_FAILED',

    FETCH_BET_RESTRICTIONS_HISTORY: 'BR::FETCH_BET_RESTRICTIONS_HISTORY',
    FETCH_BET_RESTRICTIONS_HISTORY_SUCCEEDED: 'BR::FETCH_BET_RESTRICTIONS_HISTORY_SUCCEEDED',
    FETCH_BET_RESTRICTIONS_HISTORY_FAILED: 'BR::FETCH_BET_RESTRICTIONS_HISTORY_FAILED',

    UPDATE_BET_RESTRICTIONS: 'BR::UPDATE_BET_RESTRICTIONS',
    UPDATE_BET_RESTRICTIONS_SUCCEEDED: 'BR::UPDATE_BET_RESTRICTIONS_SUCCEEDED',
    UPDATE_BET_RESTRICTIONS_FAILED: 'BR::UPDATE_BET_RESTRICTIONS_FAILED',

    UPDATE_BET_RESTRICTIONS_HISTORY: 'BR::UPDATE_BET_RESTRICTIONS_HISTORY',
    UPDATE_BET_RESTRICTIONS_HISTORY_SUCCEEDED: 'BR::UPDATE_BET_RESTRICTIONS_HISTORY_SUCCEEDED',
    UPDATE_BET_RESTRICTIONS_HISTORY_FAILED: 'BR::UPDATE_BET_RESTRICTIONS_HISTORY_FAILED',

    RESTORE_BET_RESTRICTIONS_HISTORY: 'BR::RESTORE_BET_RESTRICTIONS_HISTORY',
    RESTORE_BET_RESTRICTIONS_HISTORY_SUCCEEDED: 'BR::RESTORE_BET_RESTRICTIONS_HISTORY_SUCCEEDED',
    RESTORE_BET_RESTRICTIONS_HISTORY_FAILED: 'BR::RESTORE_BET_RESTRICTIONS_HISTORY_FAILED',

    ADD_NEW_BET_RESTRICTION: 'BR::ADD_NEW_BET_RESTRICTION',
    ADD_NEW_BET_RESTRICTION_SUCCEEDED: 'BR::ADD_NEW_BET_RESTRICTION_SUCCEEDED',
    ADD_NEW_BET_RESTRICTION_FAILED: 'BR::ADD_NEW_BET_RESTRICTION_FAILED',

    CREATE_NEW_BET_RESTRICTIONS_MATRIX: 'BR::CREATE_NEW_BET_RESTRICTIONS_MATRIX',
    CREATE_NEW_BET_RESTRICTIONS_MATRIX_SUCCEEDED: 'BR::CREATE_NEW_BET_RESTRICTIONS_MATRIX_SUCCEEDED',
    CREATE_NEW_BET_RESTRICTIONS_MATRIX_FAILED: 'BR::CREATE_NEW_BET_RESTRICTIONS_MATRIX_FAILED',

    DELETE_BET_RESTRICTIONS: 'BR::DELETE_BET_RESTRICTIONS',
    DELETE_BET_RESTRICTIONS_SUCCEEDED: 'BR::DELETE_BET_RESTRICTIONS_SUCCEEDED',
    DELETE_BET_RESTRICTIONS_FAILED: 'BR::DELETE_BET_RESTRICTIONS_FAILED',

    DELETE_BET_RESTRICTIONS_TEMPORARILY: 'BR::DELETE_BET_RESTRICTIONS_TEMPORARILY',

    DELETE_BET_RESTRICTIONS_HISTORY: 'BR::DELETE_BET_RESTRICTIONS_HISTORY',
    DELETE_BET_RESTRICTIONS_HISTORY_SUCCEEDED: 'BR::DELETE_BET_RESTRICTIONS_HISTORY_SUCCEEDED',
    DELETE_BET_RESTRICTIONS_HISTORY_FAILED: 'BR::DELETE_BET_RESTRICTIONS_HISTORY_FAILED',

    SET_ACTIVE_BET_TYPE: 'BR::SET_ACTIVE_BET_TYPE',
    SET_ACTIVE_CELL: 'BR::SET_ACTIVE_CELL',
    SET_ACTIVE_HISTORY: 'BR::SET_ACTIVE_HISTORY',
    SET_PATH_ID_FOR_EVENT: 'BR::SET_PATH_ID_FOR_EVENT',
    SET_EVALUATION_ORDER_VISIBILITY: 'BR::SET_EVALUATION_ORDER_VISIBILITY',
    UPDATE_CELL_DATA: 'BR::UPDATE_CELL_DATA',
    UPDATE_BET_RESTRICTION_KEYS: 'BR::UPDATE_BET_RESTRICTION_KEYS',
    RESET_CURRENT_DATA: 'BR::RESET_CURRENT_DATA',

    NEXT_STEP: 'BR::NEXT_STEP',
    PREVIOUS_STEP: 'BR::PREVIOUS_STEP',
    UPDATE_STEP: 'BR::UPDATE_STEP',
    RESET_STEPS: 'BR::RESET_STEPS',
    UNDO_CHANGES: 'BR::UNDO_CHANGES',
    RESET_HISTORY_DATA: 'BR::RESET_HISTORY_DATA',
    UPDATE_NEW_MATRIX_DATA: 'BR::UPDATE_NEW_MATRIX_DATA',
}

export const RESTRICTION_FLAGS = {
    MULTIPLE: {desc: 'Multiple Rules', className: 'cell-multiple', key: 'MULTIPLE'},
    REFER: {desc: 'Refer', className: 'cell-refer', key: 'REFER'},
    ALLOW: {desc: 'Allow', className: 'cell-allow', key: 'ALLOW'},
    REJECT: {desc: 'Reject', className: 'cell-reject', key: 'REJECT'},
    NO_RULE: {desc: 'No Rule', className: 'cell-no-rule', key: 'NO_RULE'},
}

export const COMMON_RULE_PROPS = {
    betRestrictionId: null,
    levelId: 0,
    levelParentId: 0,
    maxSelectionCount: 2,
    minSelectionCount: 2,
    otherFlag: 'REJECT',
    sameFlag: 'REJECT',
    tagId: 0,
}

export const NEW_BET_RESTRICTION_PROPS = [
    'betRestrictionId',
    'eventTypeId',
    'eventPathId',
    'eventPathDescription',
    'eventPath',
    'tagId',
    'phraseId',
    'marketTypeGroupId',
    'marketTypeGroupDesc',
    'marketTypeId',
    'bookTypeId',
    'periodId',
]