'use strict';

const eventCreatorCRUD = {
    CREATE_EVENT: 'CREATE_EVENT',
    CREATE_EVENT_SUCCEEDED: 'CREATE_EVENT_SUCCEEDED',
    CREATE_EVENT_FAILED: 'CREATE_EVENT_FAILED',

    UPDATE_EVENT: 'UPDATE_EVENT',
    UPDATE_EVENT_SUCCEEDED: 'CREATE_EVENT_SUCCEEDED',
    UPDATE_EVENT_FAILED: 'UPDATE_EVENT_FAILED',

    DELETE_EVENT: 'DELETE_EVENT',
    DELETE_EVENT_SUCCEEDED: 'DELETE_EVENT_SUCCEEDED',
    DELETE_EVENT_FAILED: 'DELETE_EVENT_FAILED',
};

export default eventCreatorCRUD;
