const constants = {
    'UPDATE_HEADER_BUTTONS' : 'EC::GLOBAL::UPDATE_HEADER_BUTTONS',
    'SELECT_EVENT_CREATOR_PATH': 'EC::GLOBAL::SELECT_EVENT_CREATOR_PATH',
    'CLEAR_SELECTED_EVENT_CREATOR_PATH': 'EC::GLOBAL::CLEAR_SELECTED_EVENT_CREATOR_PATH',

    'FETCH_SPORT_OTHER_OPTIONS': 'EC::FETCH_SPORT_OTHER_OPTIONS',
    'FETCH_SPORT_OTHER_OPTIONS_SUCCEEDED': 'EC::FETCH_SPORT_OTHER_OPTIONS_SUCCEEDED',
    'FETCH_SPORT_OTHER_OPTIONS_FAILED': 'EC::FETCH_SPORT_OTHER_OPTIONS_FAILED',

    'UPDATE_SAVE_BUTTON_STATE': 'EC::UPDATE_SAVE_BUTTON_STATE',

    TOGGLE_BULK_UPDATE: 'EC::TOGGLE_BULK_UPDATE'
}

export const paths = {
    SPORT: 'SPORT',
    COUNTRY: 'COUNTRY',
    LEAGUE: 'LEAGUE',
    LEAGUE_NEWGAME: 'LEAGUE_NEWGAME',
    LEAGUE_NEWRANK: 'LEAGUE_NEWRANK',
    GAME_EVENT: 'GAME_EVENT',
    RANK_EVENT: 'RANK_EVENT',
    MARKET: 'MARKET',
    GAME_RESULT : 'GAME_RESULT'
}

export const permissionsCode = {
    MANAGE_EVENTS: 350,
    DELETE: 355,
    ADD_EVENT_PATH: 360,
    ADD_EVENT_PATH_TEAM: 365,
    EDIT_EVENT_PATH_TEAM: 370,
    REMOVE_EVENT_PATH_TEAM: 375,
    ADD_EVENT_PATH_PLAYER: 380,
    EDIT_EVENT_PATH_PLAYER: 385,
    REMOVE_EVENT_PATH_PLAYER: 390,
    ADD_RANK_EVENT: 395,
    ADD_GAME_EVENT: 400,
    CHANGE_GAME_EVENT_DATE_TIME: 405,
    ENABLE_EDIT_MARKETS_DIALOG: 406,
    ENABLE_NEW_MARKETS_DIALOG: 407,
    VIEW_AND_EDIT_MARKET_LINE_PROMOTED_FLAG: 410,
    VIEW_AND_EDIT_MARKET_LINE_SHOW_WHEN_UNPRICED_FLAG: 411,
    VIEW_EVENT_PATH_AND_OPPONENT_RATINGS: 415,
    EDIT_EVENT_PATH_AND_OPPONENT_RATINGS: 416,
    MARKET_EDITOR_ENTER_RESULTS: 651,
    MARKET_EDITOR_UPDATE_RESULTS: 652,
    UPDATE_BET_RESTRICTIONS: 653,
    AUTO_SETTLEMENT: 654,
    EVENTS_CREATOR_MARKET_BET_RESTRICTIONS: 840,
    BULK_TEAM_PLAYER_REMOVAL: 970,
    ALLOW_CLOSED_MARKET_REOPENING: 1227,
    CHANGE_OPPONENTS_WITH_OPEN_MARKETS: 1460,
    CHANGE_OPPONENTS_WITH_NO_OPEN_MARKETS: 1461,
}

export const sportsCodesWithRaceCardNumber = ['USHO', 'USGR', 'GREY', 'HORS'];

export default constants;