const actionTypes = {
    //STARTUP
    STARTUP: 'STARTUP',
    STARTUP_SUCCEEDED: 'STARTUP_SUCCEEDED',
    STARTUP_FAILED: 'STARTUP_FAILED',

    //RISK MANAGER APPS
    STARTUP_APP: 'STARTUP_APP',
    STARTUP_APP_SUCCEEDED: 'STARTUP_APP_SUCCEEDED',
    STARTUP_APP_FAILED: 'STARTUP_APP_FAILED',

    //USER
    LOGIN: 'LOGIN',
    LOGIN_SUCCEEDED: 'LOGIN_SUCCEEDED',
    LOGIN_FAILED: 'LOGIN_FAILED',
    LOGOUT: 'LOGOUT',
    SET_ISLOGGEDIN: 'SET_ISLOGGEDIN',
    SET_USER_DETAILS: 'SET_USER_DETAILS',

    //APPS
    FETCH_APPS: 'FETCH_APPS',
    FETCH_APPS_SUCCEEDED: 'FETCH_APPS_SUCCEEDED',
    FETCH_APPS_FAILED: 'FETCH_APPS_FAILED',
    FETCH_RECENT_APPS: 'FETCH_RECENT_APPS',
    FETCH_RECENT_APPS_SUCCEEDED: 'FETCH_RECENT_APPS_SUCCEEDED',
    FETCH_RECENT_APPS_FAILED: 'FETCH_RECENT_APPS_FAILED',
    USE_APP: 'USE_APP',
    USE_APP_SUCCEEDED: 'USE_APP_SUCCEEDED',
    USE_APP_FAILED: 'USE_APP_FAILED',
    SIDEBAR_TOGGLE: 'SIDEBAR_TOGGLE',

    //DAILY STATISTICS
    FETCH_DAILY_STATISTICS: 'FETCH_DAILY_STATISTICS',
    FETCH_DAILY_STATISTICS_SUCCEEDED: 'FETCH_DAILY_STATISTICS_SUCCEEDED',
    FETCH_DAILY_STATISTICS_FAILED: 'FETCH_DAILY_STATISTICS_FAILED',

    //ACCUMULATOR RISKS
    FETCH_GLOBAL_ACCUMULATOR_RISKS: 'FETCH_GLOBAL_ACCUMULATOR_RISKS',
    FETCH_GLOBAL_ACCUMULATOR_RISKS_SUCCEEDED: 'FETCH_GLOBAL_ACCUMULATOR_RISKS_SUCCEEDED',
    FETCH_GLOBAL_ACCUMULATOR_RISKS_FAILED: 'FETCH_GLOBAL_ACCUMULATOR_RISKS_FAILED',

    //USER RISK PREFERENCES
    FETCH_USER_RISK_COLUMNS: 'FETCH_USER_RISK_COLUMNS',
    FETCH_USER_RISK_COLUMNS_SUCCEEDED: 'FETCH_USER_RISK_COLUMNS_SUCCEEDED',
    FETCH_USER_RISK_COLUMNS_FAILED: 'FETCH_USER_RISK_COLUMNS_FAILED',
    
    FETCH_USER_RISK_SPORTS: 'FETCH_USER_RISK_SPORTS',
    FETCH_USER_RISK_SPORTS_SUCCEEDED: 'FETCH_USER_RISK_SPORTS_SUCCEEDED',
    FETCH_USER_RISK_SPORTS_FAILED: 'FETCH_USER_RISK_SPORTS_FAILED',

    EDIT_USER_RISK_COLUMNS_AND_SPORTS: 'EDIT_USER_RISK_COLUMNS_AND_SPORTS',
    EDIT_USER_RISK_COLUMNS_AND_SPORTS_SUCCEEDED: 'EDIT_USER_RISK_COLUMNS_AND_SPORTS_SUCCEEDED',
    EDIT_USER_RISK_COLUMNS_AND_SPORTS_FAILED: 'EDIT_USER_RISK_COLUMNS_AND_SPORTS_FAILED',

    //API CONSTANTS
    FETCH_API_CONSTANTS: 'FETCH_API_CONSTANTS',
    FETCH_API_CONSTANTS_SUCCEEDED: 'FETCH_API_CONSTANTS_SUCCEEDED',
    FETCH_API_CONSTANTS_FAILED: 'FETCH_API_CONSTANTS_FAILED',

    //RISK PARAMS
    SET_RISK_FILTER_CODE: 'SET_RISK_FILTER_CODE',
    SET_RISK_FILTER_DESC: 'SET_RISK_FILTER_DESC',
    SET_RISK_FILTER_DATE: 'SET_RISK_FILTER_DATE',
    SET_RISK_FILTER_MARKET_STATUS_IDS: 'SET_RISK_FILTER_MARKET_STATUS_IDS',
    SET_RISK_FILTER_LINE: 'SET_RISK_FILTER_LINE',
    SET_RISK_FILTER_MARKET: 'SET_RISK_FILTER_MARKET',
    SET_RISK_FILTER_PERIOD: 'SET_RISK_FILTER_PERIOD',
    SET_RISK_FILTER_BOOKTYPE: 'SET_RISK_FILTER_BOOKTYPE',
    SET_RISK_FILTER_LIABILITY_TYPE: 'SET_RISK_FILTER_LIABILITY_TYPE',
    SET_RISK_FILTER_PRICE_TYPE: 'SET_RISK_FILTER_PRICE_TYPE',
    SET_RISK_FILTER_WIN_PLACE: 'SET_RISK_FILTER_WIN_PLACE',
    RESET_RISK_FILTERS: 'RESET_RISK_FILTERS',
    SET_RISK_ROW_HEIGHT: 'SET_RISK_ROW_HEIGHT',
    SET_EVENT_SEARCH_VALUE: 'SET_EVENT_SEARCH_VALUE',
    SEARCH_EVENTS: 'SEARCH_EVENTS',
    ADD_CUSTOM_DATE_FILTER: 'ADD_CUSTOM_DATE_FILTER',

    //RISK DATA
    FETCH_RISK_DATA: 'FETCH_RISK_DATA',
    FETCH_RISK_DATA_SUCCEEDED: 'FETCH_RISK_DATA_SUCCEEDED',
    FETCH_RISK_DATA_FAILED: 'FETCH_RISK_DATA_FAILED',
    UPDATE_RISK_DATA: 'UPDATE_RISK_DATA',
    CANCEL_UPDATE_RISK_DATA: 'CANCEL_UPDATE_RISK_DATA',
    UPDATE_RISK_DATA_SUCCEEDED: 'UPDATE_RISK_DATA_SUCCEEDED',
    UPDATE_RISK_DATA_FAILED: 'UPDATE_RISK_DATA_FAILED',
    CLEAR_RISK_DATA: 'CLEAR_RISK_DATA',
    COLLAPSE_EVENT: 'COLLAPSE_EVENT',
    EXPAND_EVENT: 'EXPAND_EVENT',
    EXPAND_ALL_EVENTS: 'EXPAND_ALL_EVENTS',
    FETCH_CHUNK_RISK_DATA: 'FETCH_CHUNK_RISK_DATA',
    FETCH_CHUNK_RISK_DATA_SUCCEEDED: 'FETCH_CHUNK_RISK_DATA_SUCCEEDED',
    FETCH_CHUNK_RISK_DATA_FAILED: 'FETCH_CHUNK_RISK_DATA_FAILED',

    //RISK DATA CHANGES
    ADD_UNSAVED_OUTCOME_PRICE_CHANGE: 'ADD_UNSAVED_OUTCOME_PRICE_CHANGE',
    REMOVE_UNSAVED_OUTCOME_PRICE_CHANGE: 'REMOVE_UNSAVED_OUTCOME_PRICE_CHANGE',
    CLEAR_UNSAVED_OUTCOME_PRICE_CHANGES: 'CLEAR_UNSAVED_OUTCOME_PRICE_CHANGES',
    CLEAR_SPECIFIC_UNSAVED_OUTCOME_PRICE_CHANGES: 'CLEAR_SPECIFIC_UNSAVED_OUTCOME_PRICE_CHANGES',
    SAVE_OUTCOME_PRICE_CHANGES: 'SAVE_OUTCOME_PRICE_CHANGES',
    SAVE_OUTCOME_PRICE_CHANGES_SUCCEEDED: 'SAVE_OUTCOME_PRICE_CHANGES_SUCCEEDED',
    SAVE_OUTCOME_PRICE_CHANGES_FAILED: 'SAVE_OUTCOME_PRICE_CHANGES_FAILED',
    SET_CODE_AFTER_SAVING_CHANGES: 'SET_CODE_AFTER_SAVING_CHANGES',
    SET_DESC_AFTER_SAVING_CHANGES: 'SET_DESC_AFTER_SAVING_CHANGES',
    ADD_BELOW_MINIMUM_PRICE_MARGIN: 'ADD_BELOW_MINIMUM_PRICE_MARGIN',
    REMOVE_BELOW_MINIMUM_PRICE_MARGIN: 'REMOVE_BELOW_MINIMUM_PRICE_MARGIN',

    //RESULTS VIEWER
    SET_RESULTS_VIEWER_FILTER_CODE: 'SET_RESULTS_VIEWER_FILTER_CODE',
    SET_RESULTS_VIEWER_FILTER_DESC: 'SET_RESULTS_VIEWER_FILTER_DESC',
    SET_RESULTS_VIEWER_FILTER_DATE: 'SET_RESULTS_VIEWER_FILTER_DATE',
    ADD_RESULTS_VIEWER_MARKET_STATUS_ID_FILTER: 'ADD_RESULTS_VIEWER_MARKET_STATUS_ID_FILTER',
    REMOVE_RESULTS_VIEWER_MARKET_STATUS_ID_FILTER: 'REMOVE_RESULTS_VIEWER_MARKET_STATUS_ID_FILTER',
    RESET_RESULTS_VIEWER_FILTERS: 'RESET_RESULTS_VIEWER_FILTERS',
    SET_RESULTS_VIEWER_ROW_HEIGHT: 'SET_RESULTS_VIEWER_ROW_HEIGHT',
    ADD_RESULTS_VIEWER_CUSTOM_DATE_FILTER: 'ADD_RESULTS_VIEWER_CUSTOM_DATE_FILTER',
    SET_RESULTS_VIEWER_START_TIME_SORT: 'SET_RESULTS_VIEWER_START_TIME_SORT',
    SET_RESULTS_VIEWER_COLUMN_SORT: 'SET_RESULTS_VIEWER_COLUMN_SORT',

    //RESULTS VIEWER DATA
    FETCH_RESULTS_VIEWER_DATA: 'FETCH_RESULTS_VIEWER_DATA',
    FETCH_RESULTS_VIEWER_DATA_SUCCEEDED: 'FETCH_RESULTS_VIEWER_DATA_SUCCEEDED',
    FETCH_RESULTS_VIEWER_DATA_FAILED: 'FETCH_RESULTS_VIEWER_DATA_FAILED',
    UPDATE_RESULTS_VIEWER_DATA: 'UPDATE_RESULTS_VIEWER_DATA',
    CANCEL_UPDATE_RESULTS_VIEWER_DATA: 'CANCEL_UPDATE_RESULTS_VIEWER_DATA',
    UPDATE_RESULTS_VIEWER_DATA_SUCCEEDED: 'UPDATE_RESULTS_VIEWER_DATA_SUCCEEDED',
    UPDATE_RESULTS_VIEWER_DATA_FAILED: 'UPDATE_RESULTS_VIEWER_DATA_FAILED',
    CLEAR_RESULTS_VIEWER_DATA: 'CLEAR_RESULTS_VIEWER_DATA',
    COLLAPSE_RESULTS_VIEWER_EVENT: 'COLLAPSE_RESULTS_VIEWER_EVENT',
    EXPAND_RESULTS_VIEWER_EVENT: 'EXPAND_RESULTS_VIEWER_EVENT',
    EXPAND_ALL_RESULTS_VIEWER_EVENTS: 'EXPAND_ALL_RESULTS_VIEWER_EVENTS',

    //EVENT PATH TREE
    FETCH_EVENT_PATH_TREE: 'FETCH_EVENT_PATH_TREE',
    FETCH_EVENT_PATH_TREE_SUCCEEDED: 'FETCH_EVENT_PATH_TREE_SUCCEEDED',
    FETCH_EVENT_PATH_TREE_FAILED: 'FETCH_EVENT_PATH_TREE_FAILED',
    SELECT_EVENT_PATH_TREE_SPORT: 'SELECT_EVENT_PATH_TREE_SPORT',
    SELECT_EVENT_PATH_TREE_SPORT_SUCCEEDED: 'SELECT_EVENT_PATH_TREE_SPORT_SUCCEEDED',
    SELECT_EVENT_PATH_TREE_SPORT_FAILED: 'SELECT_EVENT_PATH_TREE_SPORT_FAILED',
    RESET_EVENT_PATH_TREE: 'RESET_EVENT_PATH_TREE',
    FETCH_EVENT_MARKETS: 'FETCH_EVENT_MARKETS',
    FETCH_EVENT_MARKETS_CANCEL: 'FETCH_EVENT_MARKETS_CANCEL',
    FETCH_EVENT_MARKETS_SUCCEEDED: 'FETCH_EVENT_MARKETS_SUCCEEDED',
    FETCH_EVENT_MARKETS_FAILED: 'FETCH_EVENT_MARKETS_FAILED',


    //EVENT PATH TREE FILTERING
    SET_EVENT_PATH_TREE_SEARCH_VALUE: 'SET_EVENT_PATH_TREE_SEARCH_VALUE',
    CLEAR_EVENT_PATH_TREE_SEARCH_VALUE: 'CLEAR_EVENT_PATH_TREE_SEARCH_VALUE',
    SEARCH_EVENT_PATH_TREE: 'SEARCH_EVENT_PATH_TREE',
    SEARCH_EVENT_PATH_TREE_SUCCEEDED: 'SEARCH_EVENT_PATH_TREE_SUCCEEDED',

    //MODALS
    CLOSE_MODAL: 'CLOSE_MODAL',
    OPEN_MODAL: 'OPEN_MODAL',
    CLOSE_ALL_MODALS: 'CLOSE_ALL_MODALS',

    //OUTCOMES
    TOGGLE_OUTCOME_VISIBILITY: 'TOGGLE_OUTCOME_VISIBILITY',
    TOGGLE_OUTCOME_VISIBILITY_SUCCEEDED: 'TOGGLE_OUTCOME_VISIBILITY_SUCCEEDED',
    TOGGLE_OUTCOME_VISIBILITY_FAILED: 'TOGGLE_OUTCOME_VISIBILITY_FAILED',
    
    FETCH_OUTCOME_PRICE_BY_LINE: 'FETCH_OUTCOME_PRICE_BY_LINE',
    FETCH_OUTCOME_PRICE_BY_LINE_SUCCEEDED: 'FETCH_OUTCOME_PRICE_BY_LINE_SUCCEEDED',
    FETCH_OUTCOME_PRICE_BY_LINE_FAILED: 'FETCH_OUTCOME_PRICE_BY_LINE_FAILED',
    CANCEL_FETCH_OUTCOME_PRICE_BY_LINE: 'CANCEL_FETCH_OUTCOME_PRICE_BY_LINE',
    CLEAR_OUTCOME_PRICE_BY_LINE: 'CLEAR_OUTCOME_PRICE_BY_LINE',
    
    //OUTCOME WAGER LIMITS
    SET_OUTCOME_WAGER_LIMITS_SELECTED_OUTCOME_ID: 'SET_OUTCOME_WAGER_LIMITS_SELECTED_OUTCOME_ID',
    SET_OUTCOME_WAGER_LIMITS_SELECTED_WAGER_LIMITS_GROUP_ID: 'SET_OUTCOME_WAGER_LIMITS_SELECTED_WAGER_LIMITS_GROUP_ID',
    FETCH_OUTCOME_WAGER_LIMITS_BY_GROUP: 'FETCH_OUTCOME_WAGER_LIMITS_BY_GROUP',
    FETCH_OUTCOME_WAGER_LIMITS_BY_GROUP_SUCCEEDED: 'FETCH_OUTCOME_WAGER_LIMITS_BY_GROUP_SUCCEEDED',
    FETCH_OUTCOME_WAGER_LIMITS_BY_GROUP_FAILED: 'FETCH_OUTCOME_WAGER_LIMITS_BY_GROUP_FAILED',

    //MARKETS
    CHANGE_MARKET_STATUS: 'CHANGE_MARKET_STATUS',
    CHANGE_MARKET_STATUS_SUCCEEDED: 'CHANGE_MARKET_STATUS_SUCCEEDED',
    CHANGE_MARKET_STATUS_FAILED: 'CHANGE_MARKET_STATUS_FAILED',

    //MARKET FEED DISCONNECT
    SET_MARKET_FEED_INFO_MARKETS: 'SET_MARKET_FEED_INFO_MARKETS',
    FETCH_MARKET_FEED_INFO: 'FETCH_MARKET_FEED_INFO',
    FETCH_MARKET_FEED_INFO_SUCCEEDED: 'FETCH_MARKET_FEED_INFO_SUCCEEDED',
    FETCH_MARKET_FEED_INFO_FAILED: 'FETCH_MARKET_FEED_INFO_FAILED',
    DISCONNECT_MARKET_FROM_PRICE_FEED: 'DISCONNECT_MARKET_FROM_PRICE_FEED',
    DISCONNECT_MARKET_FROM_PRICE_FEED_SUCCEEDED: 'DISCONNECT_MARKET_FROM_PRICE_FEED_SUCCEEDED',
    DISCONNECT_MARKET_FROM_PRICE_FEED_FAILED: 'DISCONNECT_MARKET_FROM_PRICE_FEED_FAILED',
    RESET_FETCH_MARKET_FEED_INFO: 'RESET_FETCH_MARKET_FEED_INFO',
    TOGGLE_MARKET_TO_DISCONNECT: 'TOGGLE_MARKET_TO_DISCONNECT',
    TOGGLE_LINE_TO_DISCONNECT: 'TOGGLE_LINE_TO_DISCONNECT',
    RESET_MARKET_FEED_INFO: 'RESET_MARKET_FEED_INFO',

    //MARKET STATE DETAILS
    VIEW_MARKET_STATE_DETAILS: 'VIEW_MARKET_STATE_DETAILS',
    FETCH_EVENT_DETAILS: 'FETCH_EVENT_DETAILS',
    FETCH_EVENT_DETAILS_SUCCEEDED: 'FETCH_EVENT_DETAILS_SUCCEEDED',
    FETCH_EVENT_DETAILS_FAILED: 'FETCH_EVENT_DETAILS_FAILED',
    CHANGE_MARKETS_STATUS: 'CHANGE_MARKETS_STATUS',
    CHANGE_MARKETS_STATUS_SUCCEEDED: 'CHANGE_MARKETS_STATUS_SUCCEEDED',
    CHANGE_MARKETS_STATUS_FAILED: 'CHANGE_MARKETS_STATUS_FAILED',
    CHANGE_MARKET_AUTO_OPEN_TIME: 'CHANGE_MARKET_AUTO_OPEN_TIME',
    CHANGE_MARKET_AUTO_OPEN_TIME_SUCCEEDED: 'CHANGE_MARKET_AUTO_OPEN_TIME_SUCCEEDED',
    CHANGE_MARKET_AUTO_OPEN_TIME_FAILED: 'CHANGE_MARKET_AUTO_OPEN_TIME_FAILED',
    CHANGE_MARKET_CUTOFF_TIME: 'CHANGE_MARKET_CUTOFF_TIME',
    CHANGE_MARKET_CUTOFF_TIME_SUCCEEDED: 'CHANGE_MARKET_CUTOFF_TIME_SUCCEEDED',
    CHANGE_MARKET_CUTOFF_TIME_FAILED: 'CHANGE_MARKET_CUTOFF_TIME_FAILED',
    ABANDON_MARKETS: 'ABANDON_MARKETS',
    ABANDON_MARKETS_SUCCEEDED: 'ABANDON_MARKETS_SUCCEEDED',
    ABANDON_MARKETS_FAILED: 'ABANDON_MARKETS_FAILED',
    FETCH_MARKET_PERIOD_DETAILS : 'FETCH_MARKET_PERIOD_DETAILS',
    FETCH_MARKET_PERIOD_DETAILS_SUCCEEDED : 'FETCH_MARKET_PERIOD_DETAILS_SUCCEEDED',
    FETCH_MARKET_PERIOD_DETAILS_FAILED : 'FETCH_MARKET_PERIOD_DETAILS_FAILED',

    //EDIT MARKET
    SET_EDIT_MARKET_MARKETS: 'SET_EDIT_MARKET_MARKETS',
    SET_EDIT_MARKET_SELECTED_MARKET_ID: 'SET_EDIT_MARKET_SELECTED_MARKET_ID',
    FETCH_EDIT_MARKET_DETAILS: 'FETCH_EDIT_MARKET_DETAILS',
    FETCH_EDIT_MARKET_DETAILS_SUCCEEDED: 'FETCH_EVENT_DETAILS_SUCCEEDED',
    FETCH_EDIT_MARKET_DETAILS_FAILED: 'FETCH_EVENT_DETAILS_FAILED',
    SAVE_EDIT_MARKET_CHANGES: 'SAVE_EDIT_MARKET_CHANGES',
    SAVE_EDIT_MARKET_CHANGES_SUCCEEDED: 'SAVE_EDIT_MARKET_CHANGES_SUCCEEDED',
    SAVE_EDIT_MARKET_CHANGES_FAILED: 'SAVE_EDIT_MARKET_CHANGES_FAILED',
    ADD_EDIT_MARKET_PRICE_MARGIN: 'ADD_EDIT_MARKET_PRICE_MARGIN',
    REMOVE_EDIT_MARKET_PRICE_MARGIN: 'REMOVE_EDIT_MARKET_PRICE_MARGIN',

    //UPDATE MARKET CUTOFF
    UPDATE_MARKET_CUTOFF_AND_AUTOOPEN_DATETIME : 'UPDATE_MARKET_CUTOFF_AND_AUTOOPEN_DATETIME',
    UPDATE_MARKET_CUTOFF_AND_AUTOOPEN_DATETIME_SUCCEEDED : 'UPDATE_MARKET_CUTOFF_AND_AUTOOPEN_DATETIME_SUCCEEDED',
    UPDATE_MARKET_CUTOFF_AND_AUTOOPEN_DATETIME_FAILED : 'UPDATE_MARKET_CUTOFF_AND_AUTOOPEN_DATETIME_FAILED',

    //RISK ANALYSIS
    FETCH_RISK_ANALYSIS_SUMMARY: 'FETCH_RISK_ANALYSIS_SUMMARY',
    FETCH_RISK_ANALYSIS_SUMMARY_SUCCEEDED: 'FETCH_RISK_ANALYSIS_SUMMARY_SUCCEEDED',
    FETCH_RISK_ANALYSIS_SUMMARY_FAILED: 'FETCH_RISK_ANALYSIS_SUMMARY_FAILED',
    FETCH_BETS_ANALYSIS: 'FETCH_BETS_ANALYSIS',
    FETCH_BETS_ANALYSIS_SUCCEEDED: 'FETCH_BETS_ANALYSIS_SUCCEEDED',
    FETCH_BETS_ANALYSIS_FAILED: 'FETCH_BETS_ANALYSIS_FAILED',
    FETCH_RISK_MULTIPLE_SUMMARY: 'FETCH_RISK_MULTIPLE_SUMMARY',
    FETCH_RISK_MULTIPLE_SUMMARY_SUCCEEDED: 'FETCH_RISK_MULTIPLE_SUMMARY_SUCCEEDED',
    FETCH_RISK_MULTIPLE_SUMMARY_FAILED: 'FETCH_RISK_MULTIPLE_SUMMARY_FAILED',
    SET_RISK_ANALYSIS_ACTIVE_KEY: 'SET_RISK_ANALYSIS_ACTIVE_KEY',
    RESET_RISK_ANALYSIS: 'RESET_RISK_ANALYSIS',
    FETCH_BET_DATA: 'FETCH_BET_DATA',
    FETCH_BET_DATA_SUCCEEDED: 'FETCH_BET_DATA_SUCCEEDED',
    FETCH_BET_DATA_FAILED: 'FETCH_BET_DATA_FAILED',
    CLEAR_BET_DATA: 'CLEAR_BET_DATA',

    //CUSTOMER MANAGER ACCOUNT
    FETCH_MAIN_OPERATOR_PERMISSIONS: 'FETCH_MAIN_OPERATOR_PERMISSIONS',
    FETCH_MAIN_OPERATOR_PERMISSIONS_SUCCEEDED: 'FETCH_MAIN_OPERATOR_PERMISSIONS_SUCCEEDED',
    FETCH_MAIN_OPERATOR_PERMISSIONS_FAILED: 'FETCH_MAIN_OPERATOR_PERMISSIONS_FAILED',

    SEARCH_ACCOUNT: 'SEARCH_ACCOUNT',
    SEARCH_ACCOUNT_SUCCEEDED: 'SEARCH_ACCOUNT_SUCCEEDED',
    SEARCH_ACCOUNT_FAILED: 'SEARCH_ACCOUNT_FAILED',
    SEARCH_ACCOUNT_CLEAR: 'SEARCH_ACCOUNT_CLEAR',

    //RISK TRANSACTION
    FETCH_RISK_TRANSACTION_DETAILS: 'FETCH_RISK_TRANSACTION_DETAILS',
    FETCH_RISK_TRANSACTION_DETAILS_SUCCEEDED: 'FETCH_RISK_TRANSACTION_DETAILS_SUCCEEDED',
    FETCH_RISK_TRANSACTION_DETAILS_FAILED: 'FETCH_RISK_TRANSACTION_DETAILS_FAILED',
    MANUAL_SETTLE_RISK_TRANSACTION: 'MANUAL_SETTLE_RISK_TRANSACTION',
    MANUAL_SETTLE_RISK_TRANSACTION_SUCCEEDED: 'MANUAL_SETTLE_RISK_TRANSACTION_SUCCEEDED',
    MANUAL_SETTLE_RISK_TRANSACTION_FAILED: 'MANUAL_SETTLE_RISK_TRANSACTION_FAILED',

    FETCH_ACCOUNT_DETAILS: 'FETCH_ACCOUNT_DETAILS',
    FETCH_ACCOUNT_DETAILS_SUCCEEDED: 'FETCH_ACCOUNT_DETAILS_SUCCEEDED',
    FETCH_ACCOUNT_DETAILS_FAILED: 'FETCH_ACCOUNT_DETAILS_FAILED',
    FETCH_ACCOUNT_DETAILS_CLEAR: 'FETCH_ACCOUNT_DETAILS_CLEAR',

    FETCH_ACCOUNT_PERMISSIONS: 'FETCH_ACCOUNT_PERMISSIONS',
    FETCH_ACCOUNT_PERMISSIONS_SUCCEEDED: 'FETCH_ACCOUNT_PERMISSIONS_SUCCEEDED',
    FETCH_ACCOUNT_PERMISSIONS_FAILED: 'FETCH_ACCOUNT_PERMISSIONS_FAILED',
    FETCH_ACCOUNT_PERMISSIONS_CLEAR: 'FETCH_ACCOUNT_PERMISSIONS_CLEAR',

    UPDATE_ACCOUNT: 'UPDATE_ACCOUNT',
    UPDATE_ACCOUNT_SUCCEEDED: 'UPDATE_ACCOUNT_SUCCEEDED',
    UPDATE_ACCOUNT_FAILED: 'UPDATE_ACCOUNT_FAILED',

    OPEN_MODAL_CREATE_ACCOUNT: 'OPEN_MODAL_CREATE_ACCOUNT',
    CLOSE_MODAL_CREATE_ACCOUNT: 'CLOSE_MODAL_CREATE_ACCOUNT',

    OPEN_MODAL_DRAGON_PAY: 'OPEN_MODAL_DRAGON_PAY',
    CLOSE_MODAL_DRAGON_PAY: 'CLOSE_MODAL_DRAGON_PAY',

    OPEN_MODAL_DRAGON_PAY_PAYBACK: 'OPEN_MODAL_DRAGON_PAY_PAYBACK',
    CLOSE_MODAL_DRAGON_PAY_PAYBACK: 'CLOSE_MODAL_DRAGON_PAY_PAYBACK',

    OPEN_MODAL_ERROR: 'OPEN_MODAL_ERROR',
    CLOSE_MODAL_ERROR: 'CLOSE_MODAL_ERROR',

    FETCH_ORIGINS: 'FETCH_ORIGINS',
    FETCH_PACKAGES: 'FETCH_PACKAGES',
    FETCH_PRICE_FORMATS: 'FETCH_PRICE_FORMATS',
    FETCH_LINES: 'FETCH_LINES',
    FETCH_LANGUAGES: 'FETCH_LANGUAGES',
    FETCH_COUNTRIES: 'FETCH_COUNTRIES',
    FETCH_REFERRAL_METHODS: 'FETCH_REFERRAL_METHODS',
    FETCH_CURRENCIES: 'FETCH_CURRENCIES',
    FETCH_SECURITY_QUESTIONS: 'FETCH_SECURITY_QUESTIONS',
    FETCH_ACCTTYPES: 'FETCH_ACCTTYPES',

    FETCH_ORIGINS_FAILED: 'FETCH_ORIGINS_FAILED',
    FETCH_LINES_FAILED: 'FETCH_LINES_FAILED',
    FETCH_PRICE_FORMATS_FAILED: 'FETCH_PRICE_FORMATS_FAILED',
    FETCH_PACKAGES_FAILED: 'FETCH_PACKAGES_FAILED',
    FETCH_LANGUAGES_FAILED: 'FETCH_LANGUAGES_FAILED',
    FETCH_COUNTRIES_FAILED: 'FETCH_COUNTRIES_FAILED',
    FETCH_REFERRAL_METHODS_FAILED: 'FETCH_REFERRAL_METHODS_FAILED',
    FETCH_CURRENCIES_FAILED: 'FETCH_CURRENCIES_FAILED',
    FETCH_SECURITY_QUESTIONS_FAILED: 'FETCH_SECURITY_QUESTIONS_FAILED',
    FETCH_ACCTTYPES_FAILED: 'FETCH_ACCTTYPES_FAILED',

    FETCH_ORIGINS_SUCCEEDED: 'FETCH_ORIGINS_SUCCEEDED',
    FETCH_LINES_SUCCEEDED: 'FETCH_LINES_SUCCEEDED',
    FETCH_PRICE_FORMATS_SUCCEEDED: 'FETCH_PRICE_FORMATS_SUCCEEDED',
    FETCH_PACKAGES_SUCCEEDED: 'FETCH_PACKAGES_SUCCEEDED',
    FETCH_LANGUAGES_SUCCEEDED: 'FETCH_LANGUAGES_SUCCEEDED',
    FETCH_COUNTRIES_SUCCEEDED: 'FETCH_COUNTRIES_SUCCEEDED',
    FETCH_REFERRAL_METHODS_SUCCEEDED: 'FETCH_REFERRAL_METHODS_SUCCEEDED',
    FETCH_CURRENCIES_SUCCEEDED: 'FETCH_CURRENCIES_SUCCEEDED',
    FETCH_SECURITY_QUESTIONS_SUCCEEDED: 'FETCH_SECURITY_QUESTIONS_SUCCEEDED',
    FETCH_ACCTTYPES_SUCCEEDED: 'FETCH_ACCTTYPES_SUCCEEDED',

    VALIDATE_PIN: 'VALIDATE_PIN',
    VALIDATE_PIN_SUCCEEDED: 'VALIDATE_PIN_SUCCEEDED',
    VALIDATE_PIN_FAILED: 'VALIDATE_PIN_FAILED',
    CLEAR_PIN: 'CLEAR_PIN',

    OPEN_ADVANCE_ACCOUNT_SEARCH: 'OPEN_ADVANCE_ACCOUNT_SEARCH',
    CLOSE_ADVANCE_ACCOUNT_SEARCH: 'CLOSE_ADVANCE_ACCOUNT_SEARCH',

    ADVANCE_SEARCH_ACCOUNT: 'ADVANCE_SEARCH_ACCOUNT',
    ADVANCE_SEARCH_ACCOUNT_SUCCEEDED: 'ADVANCE_SEARCH_ACCOUNT_SUCCEEDED',
    ADVANCE_SEARCH_ACCOUNT_FAILED: 'ADVANCE_SEARCH_ACCOUNT_FAILED',

    ADVANCE_SEARCH_ACCOUNT_TRANSFER: 'ADVANCE_SEARCH_ACCOUNT_TRANSFER',
    ADVANCE_SEARCH_ACCOUNT_TRANSFER_SUCCEEDED: 'ADVANCE_SEARCH_ACCOUNT_TRANSFER_SUCCEEDED',
    ADVANCE_SEARCH_ACCOUNT_TRANSFER_FAILED: 'ADVANCE_SEARCH_ACCOUNT_TRANSFER_FAILED',

    INITIALIZE_CALL: 'INITIALIZE_CALL',
    INITIALIZE_CALL_SUCCEEDED: 'INITIALIZE_CALL_SUCCEEDED',
    INITIALIZE_CALL_FAILED: 'INITIALIZE_CALL_FAILED',

    END_CALL: 'END_CALL',
    END_CALL_SUCCEEDED: 'END_CALL_SUCCEEDED',
    END_CALL_FAILED: 'END_CALL_FAILED',

    FETCH_TRANSACTIONS: 'FETCH_TRANSACTIONS',
    FETCH_TRANSACTIONS_SUCCEEDED: 'FETCH_TRANSACTIONS_SUCCEEDED',
    FETCH_TRANSACTIONS_FAILED: 'FETCH_TRANSACTIONS_FAILED',

    FETCH_TRANSACTION_DETAILS: 'FETCH_TRANSACTION_DETAILS',
    FETCH_TRANSACTION_DETAILS_SUCCEEDED: 'FETCH_TRANSACTION_DETAILS_SUCCEEDED',
    FETCH_TRANSACTION_DETAILS_FAILED: 'FETCH_TRANSACTION_DETAILS_FAILED',

    FETCH_RECENT_ACCOUNTS: 'FETCH_RECENT_ACCOUNTS',
    FETCH_RECENT_ACCOUNTS_SUCCEEDED: 'FETCH_RECENT_ACCOUNTS_SUCCEEDED',
    FETCH_RECENT_ACCOUNTS_FAILED: 'FETCH_RECENT_ACCOUNTS_FAILED',

    OPEN_MODAL_END_CALL: 'OPEN_MODAL_END_CALL',
    CLOSE_MODAL_END_CALL: 'CLOSE_MODAL_END_CALL',

    OPEN_SELF_EXCLUSION_WARN_MODAL: 'OPEN_SELF_EXCLUSION_WARN_MODAL',
    CLOSE_SELF_EXCLUSION_WARN_MODAL: 'CLOSE_SELF_EXCLUSION_WARN_MODAL',
    CONFIRM_SELF_EXCLUSION_WARN: 'CONFIRM_SELF_EXCLUSION_WARN',

    OPEN_TRANSACTION_WARN_MODAL: 'OPEN_TRANSACTION_WARN_MODAL',
    CLOSE_TRANSACTION_WARN_MODAL: 'CLOSE_TRANSACTION_WARN_MODAL',

    OPEN_MODAL_ACCOUNT_ADJUSTMENT :'OPEN_MODAL_ACCOUNT_ADJUSTMENT',
    CLOSE_MODAL_ACCOUNT_ADJUSTMENT :'CLOSE_MODAL_ACCOUNT_ADJUSTMENT',

    OPEN_MODAL_ACCOUNT_TRANSFER :'OPEN_MODAL_ACCOUNT_TRANSFER',
    CLOSE_MODAL_ACCOUNT_TRANSFER :'CLOSE_MODAL_ACCOUNT_TRANSFER',

    FETCH_ACCOUNT_BALANCE:'FETCH_ACCOUNT_BALANCE',
    FETCH_ACCOUNT_BALANCE_SUCCEEDED:'FETCH_ACCOUNT_BALANCE_SUCCEEDED',
    FETCH_ACCOUNT_BALANCE_FAILED:'FETCH_ACCOUNT_BALANCE_FAILED',

    FETCH_FX_RATE:'FETCH_FX_RATE',
    FETCH_FX_RATE_SUCCEEDED:'FETCH_FX_RATE_SUCCEEDED',
    FETCH_FX_RATE_FAILED:'FETCH_FX_RATE_FAILED',

    FETCH_TRANSACTION_TYPE:'FETCH_TRANSACTION_TYPE',
    FETCH_TRANSACTION_TYPE_SUCCEEDED:'FETCH_TRANSACTION_TYPE_SUCCEEDED',
    FETCH_TRANSACTION_TYPE_FAILED:'FETCH_TRANSACTION_TYPE_FAILED',

    ADJUST_ACCOUNT:'ADJUST_ACCOUNT',
    ADJUST_ACCOUNT_SUCCEEDED:'ADJUST_ACCOUNT_SUCCEEDED',
    ADJUST_ACCOUNT_FAILED:'ADJUST_ACCOUNT_FAILED',

    CREATE_ACCOUNT:'CREATE_ACCOUNT',
    CREATE_ACCOUNT_SUCCEEDED:'CREATE_ACCOUNT_SUCCEEDED',
    CREATE_ACCOUNT_FAILED:'CREATE_ACCOUNT_FAILED',

    FETCH_DRAGON_PAY_ACCOUNT: 'FETCH_DRAGON_PAY_ACCOUNT',
    FETCH_DRAGON_PAY_ACCOUNT_SUCCEEDED: 'FETCH_DRAGON_PAY_ACCOUNT_SUCCEEDED',
    FETCH_DRAGON_PAY_ACCOUNT_FAILED: 'FETCH_DRAGON_PAY_ACCOUNT_FAILED',

    ADD_DRAGON_PAY_ACCOUNT: 'ADD_DRAGON_PAY_ACCOUNT',
    ADD_DRAGON_PAY_ACCOUNT_SUCCEEDED: 'ADD_DRAGON_PAY_ACCOUNT_SUCCEEDED',
    ADD_DRAGON_PAY_ACCOUNT_FAILED: 'ADD_DRAGON_PAY_ACCOUNT_FAILED',

    DISABLE_DRAGON_PAY_ACCOUNT: 'DISABLE_DRAGON_PAY_ACCOUNT',
    DISABLE_DRAGON_PAY_ACCOUNT_SUCCEEDED: 'DISABLE_DRAGON_PAY_ACCOUNT_SUCCEEDED',
    DISABLE_DRAGON_PAY_ACCOUNT_FAILED: 'DISABLE_DRAGON_PAY_ACCOUNT_FAILED',

    PREFER_DRAGON_PAY_ACCOUNT: 'PREFER_DRAGON_PAY_ACCOUNT',
    PREFER_DRAGON_PAY_ACCOUNT_SUCCEEDED: 'PREFER_DRAGON_PAY_ACCOUNT_SUCCEEDED',
    PREFER_DRAGON_PAY_ACCOUNT_FAILED: 'PREFER_DRAGON_PAY_ACCOUNT_FAILED',

    PAYBACK_DRAGON_PAY_ACCOUNT: 'PAYBACK_DRAGON_PAY_ACCOUNT',
    PAYBACK_DRAGON_PAY_ACCOUNT_SUCCEEDED: 'PAYBACK_DRAGON_PAY_ACCOUNT_SUCCEEDED',
    PAYBACK_DRAGON_PAY_ACCOUNT_FAILED: 'PAYBACK_DRAGON_PAY_ACCOUNT_FAILED',

    CM_ADD_ERROR: 'CM_ADD_ERROR',
    CM_CLEAR_ERROR: 'CM_CLEAR_ERROR',


    //VOID TRANSACTION
    VOID_TRANSACTION: 'VOID_TRANSACTION',
    //CANCEL TRANSACTION
    CANCEL_TRANSACTION: 'CANCEL_TRANSACTION',

    //Void or Cancel Transactions
    REVOKE_TRANSACTION:'REVOKE_TRANSACTION',
    REVOKE_TRANSACTION_SUCCEEDED:'REVOKE_TRANSACTION_SUCCEEDED',
    REVOKE_TRANSACTION_FAILED:'REVOKE_TRANSACTION_FAILED',

    //Delete Transactions
    DELETE_TRANSACTION:'DELETE_TRANSACTION',
    DELETE_TRANSACTION_SUCCEEDED:'DELETE_TRANSACTION_SUCCEEDED',
    DELETE_TRANSACTION_FAILED:'DELETE_TRANSACTION_FAILED',

    //Get ABP Settings
    FETCH_ABPSETTINGS:'FETCH_ABPSETTINGS',
    FETCH_ABPSETTINGS_SUCCEEDED:'FETCH_ABPSETTINGS_SUCCEEDED',
    FETCH_ABPSETTINGS_FAILED:'FETCH_ABPSETTINGS_FAILED',

    // Get Bet Statistics
    FETCH_BETSTATISTICS:'FETCH_BETSTATISTICS',
    FETCH_BETSTATISTICS_SUCCEEDED:'FETCH_BETSTATISTICS_SUCCEEDED',
    FETCH_BETSTATISTICS_FAILED:'FETCH_BETSTATISTICS_FAILED',

    // Get Account Statistics
    FETCH_ACCOUNTSTATS:'FETCH_ACCOUNTSTATS',
    FETCH_ACCOUNTSTATS_SUCCEEDED:'FETCH_ACCOUNTSTATS_SUCCEEDED',
    FETCH_ACCOUNTSTATS_FAILED:'FETCH_ACCOUNTSTATS_FAILED',

    // Get Account Status
    FETCH_ACCOUNTSTATUS:'FETCH_ACCOUNTSTATUS',
    FETCH_ACCOUNTSTATUS_SUCCEEDED:'FETCH_ACCOUNTSTATUS_SUCCEEDED',
    FETCH_ACCOUNTSTATUS_FAILED:'FETCH_ACCOUNTSTATUS_FAILED',

    UPDATE_ACCOUNTSTATUS: 'UPDATE_ACCOUNTSTATUS',
    UPDATE_ACCOUNTSTATUS_SUCCEEDED: 'UPDATE_ACCOUNTSTATUS_SUCCEEDED',
    UPDATE_ACCOUNTSTATUS_FAILED: 'UPDATE_ACCOUNTSTATUS_FAILED',

    ACCOUNT_TRANSFER:'ACCOUNT_TRANSFER',
    ACCOUNT_TRANSFER_SUCCEEDED:'ACCOUNT_TRANSFER_SUCCEEDED',
    ACCOUNT_TRANSFER_FAILED:'ACCOUNT_TRANSFER_FAILED',

    OPEN_MODAL_ACCOUNT_TRANSFER_SEARCH: 'OPEN_MODAL_ACCOUNT_TRANSFER_SEARCH',
    CLOSE_MODAL_ACCOUNT_TRANSFER_SEARCH: 'CLOSE_MODAL_ACCOUNT_TRANSFER_SEARCH',

    OPEN_MODAL_ACCOUNT_TRANSFER_CONFIRMATION: 'OPEN_MODAL_ACCOUNT_TRANSFER_CONFIRMATION',
    CLOSE_MODAL_ACCOUNT_TRANSFER_CONFIRMATION: 'CLOSE_MODAL_ACCOUNT_TRANSFER_CONFIRMATION',

    SELECT_ACCOUNT_TO_TRANSFER: 'SELECT_ACCOUNT_TO_TRANSFER',
    CLEAR_ACCOUNT_TO_TRANSFER: 'CLEAR_ACCOUNT_TO_TRANSFER',

    ACCOUNT_LOCK: 'ACCOUNT_LOCK',
    ACCOUNT_UNLOCK: 'ACCOUNT_UNLOCK',

    // Get account security details
    FETCH_ACCOUNTSECURITYDETAILS:'FETCH_ACCOUNTSECURITYDETAILS',
    FETCH_ACCOUNTSECURITYDETAILS_SUCCEEDED:'FETCH_ACCOUNTSECURITYDETAILS_SUCCEEDED',
    FETCH_ACCOUNTSECURITYDETAILS_FAILED:'FETCH_ACCOUNTSECURITYDETAILS_FAILED',

    // UPDATE account security details
    UPDATE_ACCOUNTSECURITYDETAILS:'UPDATE_ACCOUNTSECURITYDETAILS',
    UPDATE_ACCOUNTSECURITYDETAILS_SUCCEEDED:'UPDATE_ACCOUNTSECURITYDETAILS_SUCCEEDED',
    UPDATE_ACCOUNTSECURITYDETAILS_FAILED:'UPDATE_ACCOUNTSECURITYDETAILS_FAILED',

    // Update account security details password
    UPDATE_ACCOUNTSECURITYPASSWORD:'UPDATE_ACCOUNTSECURITYPASSWORD',
    UPDATE_ACCOUNTSECURITYPASSWORD_SUCCEEDED:'UPDATE_ACCOUNTSECURITYPASSWORD_SUCCEEDED',
    UPDATE_ACCOUNTSECURITYPASSWORD_FAILED:'UPDATE_ACCOUNTSECURITYDETAILS_FAILED',
    CONFIRM_ACCOUNTSECURITYPASSWORD: 'CONFIRM_ACCOUNTSECURITYPASSWORD',
    RESET_PASSWORDERRORMESSAGE: 'RESET_PASSWORDERRORMESSAGE',

    //Customer Manager Chat
    FETCH_CHAT_HISTORY: 'FETCH_CHAT_HISTORY',
    FETCH_CHAT_HISTORY_SUCCEEDED: 'FETCH_CHAT_HISTORY_SUCCEEDED',
    FETCH_CHAT_HISTORY_FAILED: 'FETCH_CHAT_HISTORY_FAILED',

    FETCH_CHAT_SESSION: 'FETCH_CHAT_SESSION',
    FETCH_CHAT_SESSION_SUCCEEDED: 'FETCH_CHAT_SESSION_SUCCEEDED',
    FETCH_CHAT_SESSION_FAILED: 'FETCH_CHAT_SESSION_FAILED',

    //Customer Manager Comments
    FETCH_COMMENTS: 'FETCH_COMMENTS',
    FETCH_COMMENTS_SUCCEEDED: 'FETCH_COMMENTS_SUCCEEDED',
    FETCH_COMMENTS_FAILED: 'FETCH_COMMENTS_FAILED',
    ADD_COMMENT: 'ADD_COMMENT',
    ADD_COMMENT_SUCCEEDED: 'ADD_COMMENT_SUCCEEDED',
    ADD_COMMENT_FAILED: 'ADD_COMMENT_FAILED',

    UPDATE_COMMENT: 'UPDATE_COMMENT',
    UPDATE_COMMENT_SUCCEEDED: 'UPDATE_COMMENT_SUCCEEDED',
    UPDATE_COMMENT_FAILED: 'UPDATE_COMMENT_FAILED',

    UPDATE_CC_COMMENT: 'UPDATE_CC_COMMENT',
    UPDATE_CC_COMMENT_SUCCEEDED: 'UPDATE_CC_COMMENT_SUCCEEDED',
    UPDATE_CC_COMMENT_FAILED: 'UPDATE_CC_COMMENT_FAILED',

    DELETE_COMMENT: 'DELETE_COMMENT',
    DELETE_COMMENT_SUCCEEDED: 'DELETE_COMMENT_SUCCEEDED',
    DELETE_COMMENT_FAILED: 'DELETE_COMMENT_FAILED',

    OPEN_MODAL_COMMENT: 'OPEN_MODAL_COMMENT',
    CLOSE_MODAL_COMMENT: 'CLOSE_MODAL_COMMENT',
    SELECT_COMMENT_ID: 'SELECT_COMMENT_ID',

    //Customer Manager Promo
    FETCH_PROMO_REWARDS: 'FETCH_PROMO_REWARDS',
    FETCH_PROMO_REWARDS_SUCCEEDED: 'FETCH_PROMO_REWARDS_SUCCEEDED',
    FETCH_PROMO_REWARDS_FAILED: 'FETCH_PROMO_REWARDS_FAILED',

    FETCH_ACCOUNT_MORE_DETAILS: 'FETCH_ACCOUNT_MORE_DETAILS',
    FETCH_ACCOUNT_MORE_DETAILS_SUCCEEDED: 'FETCH_ACCOUNT_MORE_DETAILS_SUCCEEDED',
    FETCH_ACCOUNT_MORE_DETAILS_FAILED: 'FETCH_ACCOUNT_MORE_DETAILS_FAILED',

    //Customer Manager Promo
    FETCH_OUTCOME_WAGERLIMIT_GROUP_INFO: 'FETCH_OUTCOME_WAGERLIMIT_GROUP_INFO',
    FETCH_OUTCOME_WAGERLIMIT_GROUP_INFO_SUCCEEDED: 'FETCH_OUTCOME_WAGERLIMIT_GROUP_INFO_SUCCEEDED',
    FETCH_OUTCOME_WAGERLIMIT_GROUP_INFO_FAILED: 'FETCH_OUTCOME_WAGERLIMIT_GROUP_INFO_FAILED',

    UPDATE_ACCOUNT_MORE_DETAILS: 'UPDATE_ACCOUNT_MORE_DETAILS',
    UPDATE_ACCOUNT_MORE_DETAILS_SUCCEEDED: 'UPDATE_ACCOUNT_MORE_DETAILS_SUCCEEDED',
    UPDATE_ACCOUNT_MORE_DETAILS_FAILED: 'UPDATE_ACCOUNT_MORE_DETAILS_FAILED',

    FETCH_PAYMENT_PROVIDERS: 'FETCH_PAYMENT_PROVIDERS',
    FETCH_PAYMENT_PROVIDERS_SUCCEEDED: 'FETCH_PAYMENT_PROVIDERS_SUCCEEDED',
    FETCH_PAYMENT_PROVIDERS_FAILED: 'FETCH_PAYMENT_PROVIDERS_FAILED',

    //Customer Manager Performance
    FETCH_PERFORMANCE_SUMMARY : 'FETCH_PERFORMANCE_SUMMARY',
    FETCH_PERFORMANCE_SUMMARY_SUCCEEDED : 'FETCH_PERFORMANCE_SUMMARY_SUCCEEDED',
    FETCH_PERFORMANCE_SUMMARY_FAILED : 'FETCH_PERFORMANCE_SUMMARY_FAILED',

    FETCH_PERFORMANCE : 'FETCH_PERFORMANCE',
    FETCH_PERFORMANCE_SUCCEEDED : 'FETCH_PERFORMANCE_SUCCEEDED',
    FETCH_PERFORMANCE_FAILED : 'FETCH_PERFORMANCE_FAILED',

    CM_OPERATOR_LOGIN: 'CM_OPERATOR_LOGIN',
    CM_OPERATOR_LOGIN_SUCCEEDED: 'CM_OPERATOR_LOGIN_SUCCEEDED',
    CM_OPERATOR_LOGIN_FAILED: 'CM_OPERATOR_LOGIN_FAILED',
    CM_OPERATOR_CLEAR_ERROR: 'CM_OPERATOR_CLEAR_ERROR',

    OPEN_MODAL_CM_OPERATOR_LOGIN: 'OPEN_MODAL_CM_OPERATOR_LOGIN',
    CLOSE_MODAL_CM_OPERATOR_LOGIN: 'CLOSE_MODAL_CM_OPERATOR_LOGIN',

    //Customer Manager Settings
    FETCH_EVENTPATHS_FROM_CODE: 'FETCH_EVENTPATHS_FROM_CODE',
    FETCH_EVENTPATHS_FROM_CODE_SUCCEEDED: 'FETCH_EVENTPATHS_FROM_CODE_SUCCEEDED',
    FETCH_EVENTPATHS_FROM_CODE_FAILED: 'FETCH_EVENTPATHS_FROM_CODE_FAILED',

    //Get Account Wager Limit
    FETCH_ACCOUNT_WAGER_LIMITS: 'FETCH_ACCOUNT_WAGER_LIMITS',
    FETCH_ACCOUNT_WAGER_LIMITS_SUCCEEDED: 'FETCH_ACCOUNT_WAGER_LIMITS_SUCCEEDED',
    FETCH_ACCOUNT_WAGER_LIMITS_FAILED: 'FETCH_ACCOUNT_WAGER_LIMITS_FAILED',
    //Save Wager Limit
    SAVE_WAGER_LIMIT: 'SAVE_WAGER_LIMIT',
    SAVE_WAGER_LIMIT_SUCCEEDED: 'SAVE_WAGER_LIMIT_SUCCEEDED',
    SAVE_WAGER_LIMIT_FAILED: 'SAVE_WAGER_LIMIT_FAILED',

    //Set Default wager limit
    SET_DEFAULT_WAGER_LIMIT: 'SET_DEFAULT_WAGER_LIMIT',
    SET_PATH_SPECIFIC_LIMITS: 'SET_PATH_SPECIFIC_LIMITS',

    //Get Profile Flags
    FETCH_PLAYER_PROFILE_FLAGS: 'FETCH_PLAYER_PROFILE_FLAGS',
    FETCH_PLAYER_PROFILE_FLAGS_SUCCEEDED: 'FETCH_PLAYER_PROFILE_FLAGS_SUCCEEDED',
    FETCH_PLAYER_PROFILE_FLAGS_FAILED: 'FETCH_PLAYER_PROFILE_FLAGS_FAILED',
    //Save Profile Flags
    SAVE_PLAYER_PROFILE_FLAG: 'SAVE_PLAYER_PROFILE_FLAG',
    SAVE_PLAYER_PROFILE_FLAG_SUCCEEDED: 'SAVE_PLAYER_PROFILE_FLAG_SUCCEEDED',
    SAVE_PLAYER_PROFILE_FLAG_FAILED: 'SAVE_PLAYER_PROFILE_FLAG_FAILED',

    //Get Account details for Settings Tab
    FETCH_ACCOUNTDETAILS_SETTINGS: 'FETCH_ACCOUNTDETAILS_SETTINGS',
    FETCH_ACCOUNTDETAILS_SETTINGS_SUCCEEDED: 'FETCH_ACCOUNTDETAILS_SETTINGS_SUCCEEDED',
    FETCH_ACCOUNTDETAILS_SETTINGS_FAILED: 'FETCH_ACCOUNTDETAILS_SETTINGS_FAILED',

    FETCH_APP_PERMISSIONS: 'FETCH_APP_PERMISSIONS',
    FETCH_APP_PERMISSIONS_SUCCEEDED: 'FETCH_APP_PERMISSIONS_SUCCEEDED',
    FETCH_APP_PERMISSIONS_FAILED: 'FETCH_APP_PERMISSIONS_FAILED',

    //EVENT CREATOR PATH TREE
    SELECT_EVENT_CREATOR_PATH: 'SELECT_EVENT_CREATOR_PATH',
    SET_EVENT_CREATOR_LOADING_VISIBILITY: 'SET_EVENT_CREATOR_LOADING_VISIBILITY',
    DELETE_EVENT_PATH: 'DELETE_EVENT_PATH',
    DELETE_EVENT_PATH_SUCCEEDED: 'DELETE_EVENT_PATH_SUCCEEDED',
    DELETE_EVENT_PATH_FAILED: 'DEL;ETE_EVENT_PATH_FAILED',
    CLEAR_DELETE_EVENT_PATH_ERRORS: 'CLEAR_DELETE_EVENT_PATH_ERRORS',
    DELETE_EVENT: 'DELETE_EVENT',
    DELETE_EVENT_SUCCEEDED: 'DELETE_EVENT_SUCCEEDED',
    DELETE_EVENT_FAILED: 'DELETE_EVENT_FAILED',
    SAVE_REORDER: 'SAVE_REORDER',
    SAVE_REORDER_SUCCEEDED: 'SAVE_REORDER_SUCCEEDED',
    SAVE_REORDER_FAILED: 'SAVE_REORDER_FAILED',
};

export default actionTypes;