import {transactionPermissions} from './transactionConstants';

const accountPermissions = {
  
  // Transactions
  'TRANSACTIONS_VIEW': 210,
  'TRANSACTIONS_ACCOUNT_TRANSFER': 441,
  'TRANSACTIONS_ADJUSTMENT': 225,
  'TRANSACTIONS_EXPORT': 215,
  ...transactionPermissions,
  
  // Security
  'SECURITY_VIEW': 245,
  'SECURITY_CHANGE_PASSWORD': 250,
  'SECURITY_CHANGE_SECURITYQUESTION': 255,
  'SECURITY_CHANGE_DOB': 260,
  'SECURITY_ALLOW_ONLINEBETS': 270,
  'SECURITY_CHANGE_SECURITYLEVEL': 640,
  'SECURITY_CHANGE_IDCARDNUMBER': 287,
  
  // Settings
  'SETTINGS_VIEW': 62,
  'SETTINGS_VIEW_WAGERLIMIT': 1210,

  // Dashboard
  'DASHBOARD_VIEW_NOTES': 125,
  'DASHBOARD_EDIT_NOTE': 145,
  'DASHBOARD_DELETE_NOTE': 150,
  'DASHBOARD_CHANGE_ACCOUNT_STATUS': 160,
  'DASHBOARD_EDIT_CREDITLIMIT': 165,
  'DASHBOARD_EDIT_TEMPORARY_CREDIT': 170,
  'DASHBOARD_CHANGE_ACCOUNT_STORE': 175,
  'DASHBOARD_VIEW_BETTING_AREA': 115,
  'DASHBOARD_YTD_AND_LT': 120,
  'DASHBOARD_UPDATE_PAYMENT_METHOD': 1213,

  // Performance
  'PERFORMANCE_VIEW': 190,
  'PERFORMANCE_SAVE': 180,
  'PERFORMANCE_PRINT': 185,

  // Contact Details
  'CONTACT_EDIT': 110,
  'CONTACT_CHANGE_CONTACT_DETAILS': 275,
  'CONTACT_CHANGE_CONTACT_PREFERENCES': 280,

  // Create Account
  'CREATE_ACCOUNT_NEW': 100,
  'CREATE_ACCOUNT_CHANGE_PACKAGE': 952,

  // Manual Transaction
  'MANUAL_TRANSACTION_ADJUSTMENT': 961,
  'MANUAL_TRANSACTION_BONUS': 962,
  'MANUAL_TRANSACTION_COMMISSION': 963,
  'MANUAL_TRANSACTION_EXTERNAL_TRANSFER': 964,
  'MANUAL_TRANSACTION_PAYMENT_RECEIPT': 960,

  // Misc
  'IGNORE_PIN_CHECK': 825,
  'ACCOUNT_TRANSFER': 1226,
  'VIEW_ALL_CUSTOMER_BRANDS': 1502

};

function allow(permission, id) {
    return permission.find((val) => {
        return val.actionId === accountPermissions[id];
    });
};

export { accountPermissions, allow };