const constans = {
  'FETCH_INITIAL_BETS_DATA': 'EC::FETCH_INITIAL_BETS_DATA',
  'FETCH_INITIAL_BETS_DATA_SUCCEEDED': 'EC::FETCH_INITIAL_BETS_DATA_SUCCEEDED',
  'FETCH_INITIAL_BETS_DATA_FAILED': 'EC::FETCH_INITIAL_BETS_DATA_FAILED',

  'FETCH_SUBSEQUENT_BETS_DATA': 'EC::FETCH_SUBSEQUENT_BETS_DATA',
  'FETCH_SUBSEQUENT_BETS_DATA_SUCCEEDED': 'EC::FETCH_SUBSEQUENT_BETS_DATA_SUCCEEDED',
  'FETCH_SUBSEQUENT_BETS_DATA_FAILED': 'EC::FETCH_SUBSEQUENT_BETS_DATA_FAILED',

  'FETCH_INITIAL_ACCOUNTS_DATA': 'EC::FETCH_INITIAL_ACCOUNTS_DATA',
  'FETCH_INITIAL_ACCOUNTS_DATA_SUCCEEDED': 'EC::FETCH_INITIAL_ACCOUNTS_DATA_SUCCEEDED',
  'FETCH_INITIAL_ACCOUNTS_DATA_FAILED': 'EC::FETCH_INITIAL_ACCOUNTS_DATA_FAILED',

  'FETCH_SUBSEQUENT_ACCOUNTS_DATA': 'EC::FETCH_SUBSEQUENT_ACCOUNTS_DATA',
  'FETCH_SUBSEQUENT_ACCOUNTS_DATA_SUCCEEDED': 'EC::FETCH_SUBSEQUENT_ACCOUNTS_DATA_SUCCEEDED',
  'FETCH_SUBSEQUENT_ACCOUNTS_DATA_FAILED': 'EC::FETCH_SUBSEQUENT_ACCOUNTS_DATA_FAILED',

  'FETCH_INITIAL_PAYMENTS_DATA': 'EC::FETCH_INITIAL_PAYMENTS_DATA',
  'FETCH_INITIAL_PAYMENTS_DATA_SUCCEEDED': 'EC::FETCH_INITIAL_PAYMENTS_DATA_SUCCEEDED',
  'FETCH_INITIAL_PAYMENTS_DATA_FAILED': 'EC::FETCH_INITIAL_PAYMENTS_DATA_FAILED',

  'FETCH_SUBSEQUENT_PAYMENTS_DATA': 'EC::FETCH_SUBSEQUENT_PAYMENTS_DATA',
  'FETCH_SUBSEQUENT_PAYMENTS_DATA_SUCCEEDED': 'EC::FETCH_SUBSEQUENT_PAYMENTS_DATA_SUCCEEDED',
  'FETCH_SUBSEQUENT_PAYMENTS_DATA_FAILED': 'EC::FETCH_SUBSEQUENT_PAYMENTS_DATA_FAILED',

  'FETCH_INITIAL_FAILEDBETS_DATA': 'EC::FETCH_INITIAL_FAILEDBETS_DATA',
  'FETCH_INITIAL_FAILEDBETS_DATA_SUCCEEDED': 'EC::FETCH_INITIAL_FAILEDBETS_DATA_SUCCEEDED',
  'FETCH_INITIAL_FAILEDBETS_DATA_FAILED': 'EC::FETCH_INITIAL_FAILEDBETS_DATA_FAILED',

  'FETCH_SUBSEQUENT_FAILEDBETS_DATA': 'EC::FETCH_SUBSEQUENT_FAILEDBETS_DATA',
  'FETCH_SUBSEQUENT_FAILEDBETS_DATA_SUCCEEDED': 'EC::FETCH_SUBSEQUENT_FAILEDBETS_DATA_SUCCEEDED',
  'FETCH_SUBSEQUENT_FAILEDBETS_DATA_FAILED': 'EC::FETCH_SUBSEQUENT_FAILEDBETS_DATA_FAILED',

  'CHANGE_BET_TYPE': 'EC::CHANGE_BET_TYPE',
  'TOGGLE_EXPAND': 'EC::TOGGLE_EXPAND',
  'TOGGLE_ACTIVE': 'EC::TOGGLE_ACTIVE',

  'TOGGLE_MARKETS_TYPE': 'EC::TOGGLE_MARKETS_TYPE',

  'CHANGE_TOTAL_STAKE_TYPE': 'EC::CHANGE_TOTAL_STAKE_TYPE',
  'CHANGE_TOTAL_STAKE_VALUE': 'EC::CHANGE_TOTAL_STAKE_VALUE',

  'CHANGE_RISK_AMOUNT_TYPE': 'EC::CHANGE_RISK_AMOUNT_TYPE',
  'CHANGE_RISK_AMOUNT_VALUE': 'EC::CHANGE_RISK_AMOUNT_VALUE',

  'CHANGE_SPORTS_TYPE': 'EC::CHANGE_SPORTS_TYPE',

  'ADD_SPORT': 'EC::ADD_SPORT',
  'REMOVE_SPORT': 'EC::REMOVE_SPORT',

  'CHANGE_MAX_ROWS': 'EC::CHANGE_MAX_ROWS',

  'CHANGE_ACTIVE_TAB_INDEX': 'EC::CHANGE_ACTIVE_TAB_INDEX',

  'CHANGE_LOWER_LIMIT': 'EC::CHANGE_LOWER_LIMIT',
  'CHANGE_UPPER_LIMIT': 'EC::CHANGE_UPPER_LIMIT',
  'CHANGE_FONT_COLOR': 'EC::CHANGE_FONT_COLOR',
  'CHANGE_BACKGROUND_COLOR': 'EC::CHANGE_BACKGROUND_COLOR',
  'ADD_FORMATTER_ITEM': 'EC::ADD_FORMATTER_ITEM',
  'REMOVE_FORMATTER_ITEM': 'EC::REMOVE_FORMATTER_ITEM',

  'LOCK_TABLE': 'EC::LOCK_TABLE',
  'UNLOCK_TABLE': 'EC::UNLOCK_TABLE',

  'SHOW_PREFERENCES_MODAL': 'EC::SHOW_PREFERENCES_MODAL',
  'HIDE_PREFERENCES_MODAL': 'EC:HIDE_PREFERENCES_MODAL',

  'SET_HEADER_PREFERENCE': 'EC::SET_HEADER_PREFERENCE',

  'SAVE_CONSTANTS_TO_STORE': 'EC::SAVE_CONSTANTS_TO_STORE',

  'CHANGE_BRAND_VALUE': 'EC::CHANGE_BRAND_VALUE',

  'REHYDRATE_STATE': 'EC::REHYDRATE_STATE',

  'REMOVE_SCROLL_TOP': 'EC::REMOVE_SCROLL_TOP'
};

export default constans;
