const constants = {
  APPLICATION_ID: 7,

  STATUS_IDS: {
    CLOSED: { desc: 'Closed', value: '1' },
    OPEN: { desc: 'Open', value: '2' },
    SUSPENDED: { desc: 'Suspended', value: '3' },
    SUSPENDED_PASSWORD_FAILURE: {
      desc: 'Suspended Password Failure',
      value: '4'
    },
    OPEN_NOT_POOL: { desc: 'Open Not Pool', value: '5' },
    SUSPENDED_EXCEPT_LOGIN: { desc: 'Suspended Except Login', value: '6' }
  },
  STATUS_ID_LIST: {
    '0': 'All',
    '1': 'Closed',
    '2': 'Open',
    '3': 'Suspended',
    '4': 'Suspended Password Failure',
    '5': 'Open Not Pool',
    '6': 'Suspended Except Login'
  },

  FETCH_OPERATOR_GROUPS: 'OM::FETCH_OPERATOR_GROUPS',
  FETCH_OPERATOR_GROUPS_SUCCEEDED: 'OM::FETCH_OPERATOR_GROUPS_SUCCEEDED',
  FETCH_OPERATOR_GROUPS_FAILED: 'OM::FETCH_OPERATOR_GROUPS_FAILED',

  // FETCH_APPLICATIONS : 'OM::FETCH_APPLICATIONS',
  // FETCH_APPLICATIONS_SUCCEEDED : 'OM::FETCH_APPLICATIONS_SUCCEEDED',
  // FETCH_APPLICATIONS_FAILED : 'OM::FETCH_APPLICATIONS_FAILED',

  // FETCH_ACTIONS : 'OM::FETCH_ACTIONS',
  // FETCH_ACTIONS_SUCCEEDED : 'OM::FETCH_ACTIONS_SUCCEEDED',
  // FETCH_ACTIONS_FAILED : 'OM::FETCH_ACTIONS_FAILED',

  // FETCH_REPORTS : 'OM::FETCH_REPORTS',
  // FETCH_REPORTS_SUCCEEDED : 'OM::FETCH_REPORTS_SUCCEEDED',
  // FETCH_REPORTS_FAILED : 'OM::FETCH_REPORTS_FAILED',

  SUBMIT_OPERATOR_DATA: 'OM::SUBMIT_OPERATOR_DATA',
  SUBMIT_OPERATOR_DATA_SUCCEEDED: 'OM::SUBMIT_OPERATOR_DATA_SUCCEEDED',
  SUBMIT_OPERATOR_DATA_FAILED: 'OM::SUBMIT_OPERATOR_DATA_FAILED',

  OPERATOR: 'OPERATOR',
  OPERATORGROUP: 'OPERATORGROUP',

  FORM_READY: 'FORM_READY',
  FORM_LOADED: 'FORM_LOADED',
  FORM_LOADING: 'FORM_LOADING',
  FORM_CHANGED: 'FORM_CHANGED',
  FORM_ERROR: 'FORM_ERROR',
  FORM_SAVING: 'FORM_SAVING',
  FORM_SAVE_SUCCESS: 'FORM_SUCCESS',
  FORM_SAVE_ERROR: 'FORM_ERROR',
  FORM_PERMISSION_SAVE_SUCCESS: 'FORM_PERMISSION_SAVE_SUCCESS',
  FORM_PERMISSION_SAVE_ERROR: 'FORM_PERMISSION_SAVE_ERROR',

  FORM_MODE_NEW: 'NEW',
  FORM_MODE_EDIT: 'EDIT',

  SHOW_OPERATOR_MODAL: 'SHOW_OPERATOR_MODAL',
  HIDE_OPERATOR_MODAL: 'HIDE_OPERATOR_MODAL',
  SHOW_OPERATOR_GROUP_MODAL: 'SHOW_OPERATOR_GROUP_MODAL',
  HIDE_OPERATOR_GROUP_MODAL: 'HIDE_OPERATOR_GROUP_MODAL',

  permissionsCode: {
    CREATE_USER: 816,
    CREATE_GROUP: 817,
    CHANGE_NON_ADMIN_USER_PASSWORD: 818,
    MOVE_USER_GROUP: 819,
    UPDATE: 821,
    INSERT: 822,
    DELETE: 823,
    CHANGE_USER_PASSWORD: 1505,
    CHANGE_USER_STATUS: 1506
  }
}

export default constants
